//@GeneratedCode
namespace QTTankpreise.Logic.DataContext
{
    ///
    /// Generated by the generator
    ///
    partial class ProjectDbContext
    {
        ///
        /// Generated by the generator
        ///
        public DbSet<Entities.Base.FuelPrice>? FuelPriceSet{ get; set; }
        
        ///
        /// Generated by the generator
        ///
        partial void GetGeneratorDbSet<E>(ref DbSet<E>? dbSet, ref bool handled) where E : Entities.EntityObject
        {
            if (typeof(E) == typeof(Entities.Base.FuelPrice))
            {
                dbSet = FuelPriceSet as DbSet<E>;
                handled = true;
            }
        }
    }
}
