//@GeneratedCode
namespace QTTankpreise.AspMvc
{
    ///
    /// Generated by the generator
    ///
    partial class Program
    {
        static partial void AddServices(WebApplicationBuilder builder)
        {
            builder.Services.AddTransient<QTTankpreise.Logic.Contracts.Base.IFuelPricesAccess, QTTankpreise.Logic.Controllers.Base.FuelPricesController>();
        }
    }
}
