//@GeneratedCode
namespace QTTankpreise.MvvMApp.Models.Base
{
    using System;
    ///
    /// Generated by the generator
    ///
    
    public partial class FuelPrice
    {
        ///
        /// Generated by the generator
        ///
        static FuelPrice()
        {
            ClassConstructing();
            ClassConstructed();
        }
        static partial void ClassConstructing();
        static partial void ClassConstructed();
        
        ///
        /// Generated by the generator
        ///
        public FuelPrice()
        {
            Constructing();
            
            Constructed();
        }
        partial void Constructing();
        partial void Constructed();
        ///
        /// Generated by the generator
        ///
        
        public System.String CompanyName { get; set; } = string.Empty;
        ///
        /// Generated by the generator
        ///
        
        public QTTankpreise.Logic.Modules.Common.PriceStatus PriceStatus { get; set; }
        ///
        /// Generated by the generator
        ///
        
        public System.Double Price { get; set; }
        ///
        /// Generated by the generator
        ///
        
        public System.String Distance { get; set; } = string.Empty;
        ///
        /// Generated by the generator
        ///
        public static QTTankpreise.MvvMApp.Models.Base.FuelPrice Create()
        {
            BeforeCreate();
            var result = new QTTankpreise.MvvMApp.Models.Base.FuelPrice();
            AfterCreate(result);
            return result;
        }
        ///
        /// Generated by the generator
        ///
        public static QTTankpreise.MvvMApp.Models.Base.FuelPrice Create(object other)
        {
            BeforeCreate(other);
            var result = new QTTankpreise.MvvMApp.Models.Base.FuelPrice();
            CommonBase.Extensions.ObjectExtensions.CopyFrom(result, other);
            AfterCreate(result, other);
            return result;
        }
        static partial void BeforeCreate();
        static partial void AfterCreate(QTTankpreise.MvvMApp.Models.Base.FuelPrice instance);
        static partial void BeforeCreate(object other);
        static partial void AfterCreate(QTTankpreise.MvvMApp.Models.Base.FuelPrice instance, object other);
        ///
        /// Generated by the generator
        ///
        public override bool Equals(object? obj)
        {
            bool result = false;
            if (obj is Models.Base.FuelPrice other)
            {
                result = Id == other.Id;
            }
            return result;
        }
        ///
        /// Generated by the generator
        ///
        public override int GetHashCode()
        {
            return this.CalculateHashCode(CompanyName, PriceStatus, Price, Distance, Id);
        }
    }
}
