//@GeneratedCode
namespace QTTankpreise.Logic.Contracts.Base
{
    using TOutModel = Models.Base.FuelPrice;
    ///
    /// Generated by the generator
    ///
    public partial interface IFuelPricesAccess : Contracts.IDataAccess<TOutModel>
    {
    }
}
